#!/usr/bin/env python3

import subprocess
import pyperclip
import os
import re

from bs4 import BeautifulSoup
from urllib.parse import urljoin

with open(os.environ["QUTE_HTML"], "r") as f:
    soup = BeautifulSoup(f)

re_type = re.compile(r"application/((rss|rdf|atom)\+)?xml|text/xml")
with open(os.environ["QUTE_FIFO"], "w") as f:
    choices = []
    for link in soup.find_all(
        "link",
        rel="alternate",
        type=re_type,
    ):
        href = urljoin(os.environ["QUTE_URL"], link.get("href"))
        type = link.get("type")
        choices.append(f"{href} | {type}")

    process = subprocess.run(
        ["wofi", "--show", "dmenu", "--insensitive", "--prompt", "News Feed"],
        input="\n".join(choices).encode(),
        capture_output=True,
    )

    stdout = process.stdout.decode().strip()
    feed = stdout.split("|")[0].strip()

    pyperclip.copy(feed)
    f.write(f'message-info "{feed} copied to the clipboard."\n')
